---
title: "LAB 03 Vitor Augusto Costa 267117"
format: html
editor: visual
---

```{r}
#| warning: false
#| message: false

library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(leaflet)

airlines <- read_csv("airlines.csv")

airports <- read_csv("airports.csv",
  col_select = c(IATA_CODE, CITY, STATE, LATITUDE, LONGITUDE)
)
processa_chunk <- function(df, pos) {
  df %>%
    filter(!str_starts(DESTINATION_AIRPORT, "1")) %>%
    drop_na() %>%
    group_by(DESTINATION_AIRPORT) %>%
    summarise(
      soma_atraso = sum(ARRIVAL_DELAY),
      n_voos = n(),
      .groups = "drop"
    )
}

estatisticas_parciais <- read_csv_chunked(
  file = "flights.csv",
  callback = DataFrameCallback$new(processa_chunk),
  chunk_size = 1000000,
  col_types = cols_only(
    DESTINATION_AIRPORT = col_character(),
    ARRIVAL_DELAY = col_double()
  )
)
flights <- estatisticas_parciais %>%
  group_by(DESTINATION_AIRPORT) %>%
  summarise(
    soma_atraso_total = sum(soma_atraso),
    n_voos_total = sum(n_voos),
    .groups = "drop"
  ) %>%
  mutate(ARRIVAL_DELAY_MEAN = soma_atraso_total / n_voos_total) %>%
  select(DESTINATION_AIRPORT, ARRIVAL_DELAY_MEAN)
```

```{r}
aeroportos_ausentes <- anti_join(
  flights, 
  airports, 
  by = c("DESTINATION_AIRPORT" = "IATA_CODE")
)
print(aeroportos_ausentes)
flights <- flights %>%
  left_join(
    airports %>% select(IATA_CODE, CITY, STATE), 
    by = c("DESTINATION_AIRPORT" = "IATA_CODE")
  )
```

```{r}
aeroportos_por_estado <- airports %>%
  count(STATE, name = "NUM_AEROPORTOS") %>%
  arrange(desc(NUM_AEROPORTOS))
print(aeroportos_por_estado)
```

```{r}
flights_coordenadas <- flights %>%
  left_join(
    airports %>% select(IATA_CODE, LATITUDE, LONGITUDE),
    by = c("DESTINATION_AIRPORT" = "IATA_CODE")
  ) %>%
  drop_na(LATITUDE, LONGITUDE)
this <- leaflet(data = flights_coordenadas) %>%
  addTiles() %>%
  addMarkers(
    lat = ~LATITUDE,
    lng = ~LONGITUDE,
    popup = ~paste(
      "<b>Aeroporto:</b>", DESTINATION_AIRPORT, "<br>",
      "<b>Cidade:</b>", CITY, "-", STATE, "<br>",
      "<b>Atraso Médio:</b>", round(ARRIVAL_DELAY_MEAN, 2), "minutos"
    )
  )
this
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
