---
title: "LAB04VitorAugustoCosta267117"
format: pdf
editor: visual
---

### 1)

```{r}
#| message: false
#| warning: false
library(readxl)
library(tidyverse)
```

### 2)

```{r}
fname <- "./WDIEXCEL.xlsx"
file.exists(fname)
```

### 3)

```{r}
countries <- read_excel(fname, sheet = "Country")
```

### 4)

```{r}
paises_escolhidos <- c("BRA", "ARG", "CHL", "COL", "MEX")

countries <- countries %>% 
  filter(`Country Code` %in% paises_escolhidos)
```

### 5)

```{r}
#| message: false
#| warning: false
WDI <- read_csv("WDIEXCEL-Data.csv")
## pra nao estourar a memoria do positcloud, no chunk5 eu transformei os dados
## excel em csv e peguei apenas a DATA pra conseguir fazer o exercicio, se nao
## ele nao rodava nem com reza.
WDI <- WDI %>% 
  filter(`Country Code` %in% paises_escolhidos) %>% 
  filter(`Indicator Code` == "SP.DYN.CBRT.IN")
```

### 6)

```{r}
WDI <- WDI %>% 
  select(`Country Code`, `Indicator Code`, as.character(1960:2018))

### tem que usar crase quando tem espaco no nome das variaveis
```

### 7)

```{r}
WDI <- WDI %>% 
  pivot_longer(
    cols = as.character(1960:2018), 
    names_to = "YEAR", 
    values_to = "SP.DYN.CBRT.IN" 
  ) %>% 
  mutate(YEAR = as.integer(YEAR))
```

### 8)

```{r}
WDI <- WDI %>% 
  mutate(YEAR = as.integer(YEAR))
```

### 9)

```{r}
WDI <- WDI %>% 
  left_join(countries, by = "Country Code") %>% 
  select(`Country Code`, `Short Name`, YEAR, SP.DYN.CBRT.IN)
```

### 10)

```{r}
WDI <- WDI %>% 
  arrange(`Short Name`, YEAR)
```

### 11)

```{r}
ggplot(WDI, aes(x = YEAR, y = SP.DYN.CBRT.IN, color = `Short Name`)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Evolução da Taxa de Natalidade (1960-2018)",
    x = "Ano",
    y = "Taxa de Natalidade (SP.DYN.CBRT.IN)",
    color = "País"
  ) +
  theme_minimal()
```

horario

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
